project_list/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :projects

end

project_list/app/models/project.rb
class Project < ActiveRecord::Base
end

project_list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

project_list/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@projects = Project.all
	end
end

project_list/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def show
		@project = Project.find params[:id]
	end


	def new
		@project = Project.new
	end


	def create
		@project = Project.create que_params
		redirect_to root_path
	end


	def edit
		@project = Project.find params[:id]
	end


	def update
		@project = Project.find params[:id]
		@project.update_attributes que_params
		redirect_to root_path
	end	


	def destroy
	@project = Project.find params[:id]
    @project.delete
    redirect_to root_path
	end
	

private
	def que_params
		params.require(:project).permit(:name)
	end

end

project_list/app/helpers/application_helper.rb
module ApplicationHelper
end

project_list/app/helpers/home_helper.rb
module HomeHelper
end

project_list/app/helpers/projects_helper.rb
module ProjectsHelper
end

project_list/app/views/home/index.html.erb
<h1>YAY</h1>

  <%= link_to "New Project", new_project_path %>
  <br>
  <% @projects.each do |project| %>
  	<%= link_to project.name, project_path(project) %>
  	<%= link_to "Edit", edit_project_path(project) %>
  	<%= link_to "Delete", project_path(project), method: :delete%>
  	<br>
  	
  <% end %>

project_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

project_list/app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= form_for @project do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit %>
<% end %>

project_list/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_for @project do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.submit %>
<% end %>

project_list/app/views/projects/show.html.erb
<h1>Show data</h1>

<%= @project.name %>

<%= link_to "Home", root_path %>